name: todoist_automations

on:
  schedule:
    - cron: '00 * ? * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run todoist_automation
      env:
        TODOIST_API_KEY: ${{ secrets.TODOIST_API_KEY }}
        RECLAIM_TOKEN: ${{ secrets.RECLAIM_TOKEN }}
      run: |
        python automations.py reclaim
